---
title: "GLM HW2 Jieqi"
author: "Jieqi Tu"
date: "2/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## 4.36

```{r Q4.36}
set.seed(3)
n <- 25
x <- runif(n, 0, 100)
sigma <- 10
error <- rnorm(n, 0, sd = sigma)
y <- 45 + 0.1*x + 5e-4*x^2 + 5e-7*x^3 + 5e-10*x^4 + 5e-13*x^5 + error
true_y <- y - error
## simple model
simple_model <- lm(y~x)
## correct model
correct_model <- lm(y~poly(x,5))
## visualization
xy <- data.frame(x,y,true_y=true_y)

xy %>% ggplot() + 
  aes(x = x, y = y) + 
  geom_point() + 
  geom_smooth(method = "lm", formula = y~x, se = F, aes(color="Simple model")) + 
  geom_smooth(method = "lm", formula = y~poly(x, 5), se = F, aes(color="Correct model")) +
  geom_line(aes(x = x, y = true_y, color="True relationship"), size = 1) +
  scale_colour_manual(name="legend", values=c("blue", "red", "green")) + theme_bw()
summary(correct_model)

## quality of fit
mean(abs(simple_model$fitted.values - y))
mean(abs(correct_model$fitted.values - y))
```
